version: '3.8'

volumes:
  mdb_data:
    device: /home/fvieira/data/mariadb
  wp_data:
    device: /home/fvieira/data/wordpress

networks:
    network:
        driver: bridge

services:
    mariadb:
        hostname: mariadb
        volumes:
            -mdb_data:/var/lib/mysql
        build:
            -./requirements/mariadb/.
        ports:
            -3306:3306
        restart: always
        env_file:
            - .env
        networks:
            - network
    wordpress:
        hostname: wordpress
        volumes:
            -wp_data:/var/www/html
        build:
            -./requirements/wordpress/.
        ports:
            -9000:9000
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - network
    nginx:
        hostname: nginx
        volumes:
            -wp_data:/var/www/html
        build:
            -./requirements/nginx.
        ports:
            -443:443
        networks:
            - network
        restart: always