version: '3.8'
volumes:
  mdb_data:
  wp_data:

services:
    wordpress:
        volumes:
            -wp_data:containerPath:ro
        ports:
            -"ainda nao sei"
        restart: always
        environment:
            - vai ser=em ficheiro .env
    mariadb:
        volumes:
            -mdb_data:containerPath:ro
        ports:
            -"ainda nao sei"
        restart: always
        environment:
            - vai ser=em ficheiro .env
    nginx:
        ports:
            -"ainda nao sei"
        restart: always
        environment:
            - vai ser=em ficheiro .env