version: '3.8'
volumes:
  mdb_data:
  wp_data:
  nginx_data:
    device:

services:
    mariadb:
        volumes:
            -mdb_data:containerPath:ro
        build:
            -./requirements/mariadb/.
        ports:
            -"ainda nao sei"
        restart: always
        env_file:
            - .env
    wordpress:
        volumes:
            -wp_data:containerPath:ro
        build:
            -./requirements/wordpress/.
        ports:
            -"ainda nao sei"
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        links: 
            -mariadb
    nginx:
        volumes:
            -nginx_data
        build:
            -./requirements/nginx.
        ports:
            -"ainda nao sei"
        links:
            -wordpress
        restart: always