version: '3.8'
volumes:
  mdb_data:
  wp_data:

services:
    mariadb:
        volumes:
            -mdb_data:containerPath:ro
        ports:
            -"ainda nao sei"
        restart: always
        env_file:
            - .env
    wordpress:
        volumes:
            -wp_data:containerPath:ro
        ports:
            -"ainda nao sei"
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        links: 
            -mariadb
    nginx:
        volumes:
        ports:
            -"ainda nao sei"
        links:
            -wordpress
        restart: always