version: '3.8'

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/fvieira/data/mariadb
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/fvieira/data/wordpress

networks:
    network:
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        image: mariadb:prod
        volumes:
            - mariadb:/var/lib/mysql
        build: ./requirements/mariadb/.
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - .env
        networks:
            - network
    wordpress:
        container_name: wordpress
        image: wordpress:prod
        volumes:
            - wordpress:/var/www/html
        build: ./requirements/wordpress/.
        ports:
            - "9000:9000"
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - network
    nginx:
        container_name: nginx
        volumes:
            - wordpress:/var/www/html
        build: ./requirements/nginx/.
        ports:
            - "443:443"
        networks:
            - network
        restart: always