volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/mariadb
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/wordpress

networks:
    network:
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        init: true
        volumes:
            - mariadb:/var/lib/mysql
        build: 
            context: requirements/mariadb/.
        ports:
            - "3306:3306"
        restart: on-failure
        env_file:
            - .env
        networks:
            - network

    wordpress:
        container_name: wordpress
        volumes:
            - wordpress:/var/www/html/
        build: 
            context: requirements/wordpress/.
        ports:
            - "9000:9000"
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - network

    nginx:
        container_name: nginx
        volumes:
            - wordpress:/var/www/html/
        build: 
            context: requirements/nginx/.
        ports:
            - "443:443"
        networks:
            - network
        env_file:
            - ./.env
        depends_on:
            - wordpress
        restart: on-failure